site_name: Raiane News
site_url: https://raianecardoso.github.io/raiane-news/
theme:
  name: material
  language: pt
  palette:
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Modo claro
    - scheme: defaut
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo Escuro

  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: images/favicon.png

  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest

plugins:
  - blog
  - search

markdown_extensions: 
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg